search_query: topic:sirefaso fork:true
self_url: https://nikolat.github.io/sirefaso/
site_title: 偽SiReFaSo
site_description: GitHubで公開されている伺か関連アプリの更新情報を一覧表示する
redirect:
  Taromati2/Taromati2: Taromati2/stable-mirror
